plugins {
    id "com.android.application"
}

android {
    namespace "com.autoopenapp"
    compileSdk 36

    defaultConfig {
        applicationId "com.autoopenapp"
        minSdk 26
        targetSdk 36
        versionCode 19
        versionName "2.8.0"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
